version: '3.7'
services:

    database:
        container_name: dfwitb-db
        build:
            context: ./services/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}"
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - "3306:3306"
        volumes:
            - "./services/mysql/data:/var/lib/mysql"

    symfony: 
        container_name: dfwitb-symfony
        build:
            context: ./
            dockerfile: ./services/symfony/Dockerfile
        volumes:
            - "./app:/var/www/symfony"
            - /var/www/symfony/vendor
            - /var/www/symfony/var
        environment: 
            WAIT_HOSTS: "database:3306"
        ports:
            - "80:80"
        depends_on:
            - database
