version: '3.7'
services:

    database:
        container_name: dfwitb-db
        build:
            context: ./services/mysql
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - "3306:3306"
        volumes:
            - "./services/mysql/data:/var/lib/mysql"

    symfony: 
        container_name: dfwitb-symfony
        build:
            context: ./
            dockerfile: ./services/symfony/Dockerfile
        volumes:
            - "./app:/app"
            - /app/vendor
        ports:
            - "80:80"
